<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="regression" duration-ms="5835" started-at="2022-07-06T18:49:55 CDT" finished-at="2022-07-06T18:50:01 CDT">
    <groups>
    </groups>
    <test name="loginTest" duration-ms="5835" started-at="2022-07-06T18:49:55 CDT" finished-at="2022-07-06T18:50:01 CDT">
      <class name="test.AddContactTest">
        <test-method status="FAIL" signature="validUserShouldBeAbleToAddCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:test.AddContactTest@33f88ab]" name="validUserShouldBeAbleToAddCustomer" duration-ms="5788" started-at="2022-07-06T18:49:55 CDT" finished-at="2022-07-06T18:50:01 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[demo@Techfios.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Excel Projet]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Techfios]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[msexcell@gmail.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[231546]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Techfios Building]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Carrolton]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[United Kingdom]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[TX]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[75019]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[wrong Page ! ! expected [Dashboard- iBilling] but found [Dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: wrong Page ! ! expected [Dashboard- iBilling] but found [Dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at page.DashboardPage.validationDashboard(DashboardPage.java:27)
at test.AddContactTest.validUserShouldBeAbleToAddCustomer(AddContactTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserShouldBeAbleToAddCustomer -->
      </class> <!-- test.AddContactTest -->
    </test> <!-- loginTest -->
  </suite> <!-- regression -->
</testng-results>
